language: objective-c
osx_image: xcode11
xcode_workspace: iOS-SDK.xcworkspace
xcode_scheme: iOS-SDK
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11
before_install:
- pod update
script:
â€“ fastlane ios coverage
